name: Build memory 2026

on:
  workflow_run:
    workflows: ["Test memory 2026"]
    branches: [develop]
    types:
      - completed
  workflow_dispatch:

jobs:
  build-memory-2026:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Build project
        run: |
          docker build -t edurn/memory-2026 .
