name: Test memory 2026

on:
  push:
    branches:
      - develop

jobs:
  test-memory-2026:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Check JPEG
        run: |
          jpg_files=$(find . -name "*.jpg" -type f)

          for file in $jpg_files; do
            output=$(file "$file")
            if [[ $output != *"JPEG image data"* ]]; then
              echo "JPEG corrompu: $file"
              cp ./html/data/placeholder.jpg "$file"
              echo "Remplace $file avec ./html/data/placeholder.jpg"
            fi
          done
